// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsBackend.DataAccess;

#nullable disable

namespace ProductsBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817040830_RemoveFieldsDescAndType")]
    partial class RemoveFieldsDescAndType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductsBackend.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Café Especial",
                            Price = 19.90m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chá Verde Orgânico",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chocolate 70% Cacau",
                            Price = 8.75m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biscoito Integral",
                            Price = 6.40m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Suco de Laranja Natural",
                            Price = 9.90m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Água Mineral com Gás",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Granola Premium",
                            Price = 15.20m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Iogurte Grego",
                            Price = 7.80m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Barra de Proteína",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Leite Vegetal de Amêndoas",
                            Price = 11.30m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Molho de Tomate Artesanal",
                            Price = 5.90m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pão de Fermentação Natural",
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Queijo Minas Frescal",
                            Price = 14.80m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Azeite de Oliva Extra Virgem",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mel Orgânico",
                            Price = 18.40m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Farinha de Aveia",
                            Price = 6.90m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Mix de Castanhas",
                            Price = 16.75m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Vinagre de Maçã",
                            Price = 7.20m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sabonete Natural de Lavanda",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Shampoo Vegano",
                            Price = 17.60m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
